openapi: 3.0.0
info:
  version: 1.0.0
  title: Expense API
  description: API to handle own expenses
servers:
  - url: https://localhost/api/
tags:
  - name: expenses
paths:
  /expenses:
    get:
      tags:
        - expenses
      description: Returns a array of expenses
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Expense'
                  total:
                    type: integer
                items:
                  type: array

        '500':
          $ref: '#/components/responses/500Error'
components:
  schemas:
    Expense:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
        amount:
          type: integer
        category:
          type: string
        shop:
          type: string
  responses:
    400Error:
      description: Invalid request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid value
    404Error:
      description: Not found
      content:
        text/plain:
          schema:
            type: string
            example: Not found
    500Error:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal error
